# Starter pipeline

trigger:
- master

pr:
- master

variables:
  solutionPath: TheHub 

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - script: dotnet build -c Release
    displayName: dotnet build
    workingDirectory: $(solutionPath)

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '$(solutionPath)'
      arguments: '-c Release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'
      testRunTitle: 'ubuntu'
      
  - task: PublishCodeCoverageResults@1
    displayName: 'publish code coverage'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
      failIfCoverageEmpty: true

      
  - script: dotnet publish -c Release -o ../publish
    displayName: dotnet publish
    workingDirectory: $(solutionPath)


