apiVersion: apps/v1
kind: Deployment
metadata:
  name: TheHub-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: TheHub
      role: front
  template:
    metadata:
      labels:
        app: TheHub
        role: front
    spec:
      containers:
      - name: front
        image: proj2ui:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 128Mi